# Generated by Django 4.1.1 on 2023-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('json_user_stories', models.JSONField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Diagram_Text',
            },
        ),
    ]
