# Generated by Django 4.1.1 on 2023-09-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diagramtext',
            table='diagram_text',
        ),
    ]
