# Generated by Django 4.1.1 on 2023-09-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('microservice', '0002_alter_diagramtext_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramtext',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
